### ISSUE TITLE
"Listen" sometimes links unavailable videos

### ISSUE THREAD

**Issue by jgriesemer1** [DJUMI/CrateDigger#12]
**Describe the bug**
400 errors when clicking "Listen" from Dig. I was not able to reproduce after the first time.

**To Reproduce**
1. Go to Dig
2. View an album
3. Select Listen

**Expected behavior**
A youtube video should appear

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8

**Suggestions**
- Make sure all links are viable.

**Severity**
- Low, Trivial

**Comment by mjlatham** [comment]
Can't fix this. Some links go dead. Issue with Discogs data.
