### ISSUE TITLE
Genre filter not fully functional on dig page

### ISSUE THREAD

**Issue by tjohnson33** [DJUMI/CrateDigger#18]
**Describe the bug**
On the dig page, when you select a genre for filtering, it does not appear to affect the returned results.

**To Reproduce**
1. Go to the Dig page
2. Click "Genre" then select a genre
4. See error : doesn't appear to filter out albums

**Expected behavior**
-When a filter is applied, only albums of that genre will appear. 

**Screenshots**
- N/A

**Smartphone (please complete the following information):**
 - OS: iOS/Android

**Additional context**
- It appears that the filter isn't working, but it could just be that the website used to collect data on the album is returning weird data or classifying 

**Recommendations**
- Implement functional filtering

**Severity**
- Medium / Not-critical

**Comment by mjlatham** [comment]
This only happens for the currently displayed album; it doesn't refresh that first album in the card stack
