### ISSUE TITLE
Dig Screen Show Cancel as Filter Type

### ISSUE THREAD

**Issue by jakegriesmaier** [DJUMI/CrateDigger#20]
**Describe the bug**
-If you Select Cancel in the filter options, the filter appears as "Cancel"

**To Reproduce**
-Go to the Dig Screen 
-Select the Genre button
-Select "cancel"

**Expected behavior**
-Selecting "cancel" should remove any existing filters and show "All" at the top

**Screenshots**
![Screenshot_20191124-170324_Expo](https://user-images.githubusercontent.com/31197385/69503130-69de6d00-0edc-11ea-893b-c1fb3d50d87c.jpg)

**Smartphone (please complete the following information):**
 -Android and IOS

**Additional context**
-Happens on both Android and IOS

**Recommendations**
-remove "cancel" button, you already have a "none" option

**Severity**
-Low, Trivial

**Comment by mjlatham** [comment]
Changed it to "All", as they have the same functionality
