### ISSUE TITLE
npm issue

### ISSUE THREAD

**Issue by tjohnson33** [DJUMI/CrateDigger#24]
**Describe the bug**
- After running into an issue being stuck on the search page, I was forced to restart the app on my phone. When I did this I noticed that the application had crashed and I needed to rerun "npm start"

**To Reproduce**
- Unable to reproduce consistently, possible timeout issue

**Expected behavior**
- The client will not crash when an issue occurs

**Screenshots**
```
16:18
80

      throw er; // Unhandled 'error' event

      ^



Error: read ECONNRESET

    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)

Emitted 'error' event at:

    at emitErrorNT (internal/streams/destroy.js:91:8)

    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)

    at processTicksAndRejections (internal/process/task_queues.js:77:11) {

  errno: 'ECONNRESET',

  code: 'ECONNRESET',

  syscall: 'read'

}
```

**Smartphone (please complete the following information):**
 - OS: Android

**Additional context**
- Could not reproduce consistently, possibly a timeout error

**Recommendations**
- Test more thoroughly on android, will make finding specific device issues easier

**Severity**
- High/ High

**Comment by mjlatham** [comment]
Not an issue with our app - issue with Expo client and/or your network.
