### ISSUE TITLE
Sometimes albums will not load in main screen

### ISSUE THREAD

**Issue by jakespeare** [DJUMI/CrateDigger#8]
**Describe the bug**
Sometimes upon opening the app, none of the albums end up loading.
**Severity**
High - Blocker
**Additional Context Suggestions**
We are unable to reliably reproduce the bug. It happens rarely upon a fresh launch of the app.

**Comment by mjlatham** [comment]
Could be an issue with Expo? May not happen in a production version of the app. Will do more testing.
